import Head from 'next/head';
import styles from '../styles/Home.module.css';
import dynamic from 'next/dynamic';

// Loading component for dynamic imports
const LoadingComponent = () => (
  <div className={styles.container}>
    <div>Loading wallet...</div>
  </div>
);

// Dynamically import wallet components to avoid SSR issues
const WalletProvider = dynamic(
  () => import('@razorlabs/razorkit').then((mod) => ({ default: mod.WalletProvider })),
  { ssr: false, loading: LoadingComponent }
);

const App = dynamic(() => import('../components/App'), { ssr: false, loading: LoadingComponent });

export default function Home() {
  return (
    <WalletProvider>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <App />
      </div>
    </WalletProvider>
  );
}
